export type AiWorkItem = {
  id: string;
  title: string;
  kind: "flagship" | "workflow" | "operating-layer" | "supporting";
  group: string;
  kicker: string;
  headline: string;
  summary: string;
  caseStudy?: string;
  url?: string;
  tags: string[];
  languages: string[];
  technology: string[];
  presentation: string;
};

export const aiWork: AiWorkItem[] = [
  {
    id: "singularity-seo",
    title: "Singularity SEO",
    kind: "flagship",
    group: "Flagship Systems",
    kicker: "AI managed SEO infrastructure",
    headline: "Search, answers, action, and measurement in one operating loop.",
    summary: "Singularity SEO turns ChatGPT into the control room for a connected WordPress site. It combines technical auditing, competitive research, SEO and AIO recommendations, governed approvals, Google Search Console data, and live rank tracking without handing public publishing authority to the model.",
    caseStudy: "A production WordPress plugin and ChatGPT app with read only baselines, explicit proposal queues, approval before public changes, and rollback ready change records.",
    url: "https://singularity-mauve-phi.vercel.app/",
    tags: ["AI Operations", "Brand", "Hospitality", "Creative", "Growth", "SEO", "AIO"],
    languages: ["PHP", "TypeScript", "JavaScript", "SQL", "HTML", "CSS"],
    technology: ["WordPress", "ChatGPT Apps", "Supabase", "PostgreSQL", "REST APIs", "Google Search Console", "GA4", "SerpApi", "JSON-LD", "Vercel"],
    presentation: "Singularity SEO is AI managed SEO infrastructure. It connects a WordPress site to a ChatGPT control room that can audit the site, study competitors, build page level SEO and answer engine recommendations, and measure what happens next. Public changes remain governed. The system works read only first, creates an explicit proposal, requires approval to apply it, and preserves a rollback record for every change.",
  },
  {
    id: "conversion-forge",
    title: "Conversion Forge",
    kind: "workflow",
    group: "Creative Suite",
    kicker: "Governed copy experimentation",
    headline: "Strategic variety, tested with discipline.",
    summary: "Generates strategically distinct copy from approved brand evidence, enforces claim and voice standards, gives selection to a marketer, and writes validated strategy back into the brand library.",
    caseStudy: "A treasury platform headline test produces six different arguments, clears policy and voice gates, and ships a statistically valid winner with the learning recorded.",
    url: "https://adamcagle.com/conversion-forge/",
    tags: ["Creative", "Brand", "Fintech", "Financial", "Copywriting", "Growth"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "RAG", "Multi-model routing", "Semantic deduplication", "Policy judges", "Sequential testing", "Human approval"],
    presentation: "Conversion Forge is for brands that want tested arguments, not more volume. A structured brief and approved proof feed six genuinely different strategy lanes across multiple model families. Independent checks enforce claims and voice. A marketer chooses the test pair. The experiment applies a stopping rule and a conversion quality guardrail, then records the strategy that won so the next brief begins with evidence instead of recycled copy.",
  },
  {
    id: "synthetic-audience-lab",
    title: "Synthetic Audience Lab",
    kind: "workflow",
    group: "Creative Suite",
    kicker: "Evidence governed audience research",
    headline: "Test the hypothesis before buying the media.",
    summary: "Builds reproducible synthetic panels from governed first party evidence, separates persona authorship from response, checks for artificial consensus, and delivers testable hypotheses with confidence bands.",
    caseStudy: "A casino resort evaluates a midweek loyalty offer across four guest segments with responsible gaming exclusions applied before segmentation.",
    url: "https://adamcagle.com/synthetic-audience-lab/",
    tags: ["Creative", "Brand", "Hospitality", "Financial", "Research", "Responsible Gaming"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Multi-model panels", "PII controls", "Deterministic segmentation", "Confidence bands", "Human review"],
    presentation: "Synthetic Audience Lab makes synthetic research defensible. It starts with governed first party evidence, removes direct identifiers, applies policy exclusions, and builds a panel across independent model families. The family that writes a persona does not answer as that persona. A separate audit looks for artificial agreement, results carry confidence bands, and accountable researchers decide which hypotheses deserve a live test.",
  },
  {
    id: "crit",
    title: "CRIT",
    kind: "workflow",
    group: "Creative Suite",
    kicker: "Governed creative review",
    headline: "Every claim proven. Every component reviewed.",
    summary: "Locks the brief, reviews a campaign component by component for strategy, claims, voice, craft, accessibility, and rights, then repairs only what fails.",
    caseStudy: "A trail shoe campaign clears a supported grip claim, removes unsupported injury language, repairs the voice over, and reaches a documented Creative Director approval.",
    url: "https://adamcagle.com/crit/",
    tags: ["Creative", "Brand", "Copywriting", "AI Operations", "Compliance", "Accessibility"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Multimodal vision", "Claims extraction", "Voice rubrics", "Accessibility checks", "Rights review", "Immutable audit records"],
    presentation: "CRIT is a creative review system for campaigns that must meet real brand, legal, and accessibility standards. It locks the brief before opening the work, decomposes the campaign into addressable components, verifies explicit and implied claims, measures voice and craft, and sends rights decisions to a named owner. Repair stays bounded to what failed. The Creative Director makes the final call with a complete record of every check and change.",
  },
  {
    id: "canon",
    title: "Canon",
    kind: "workflow",
    group: "Creative Suite",
    kicker: "Governed claims and brand intelligence",
    headline: "One place the brand is allowed to speak from.",
    summary: "Turns primary evidence and approved work into a signed, versioned source of substantiated claims and measurable voice standards, then serves only what each market and channel may use.",
    caseStudy: "An outdoor company releases thirty four approved jacket claims across four markets with evidence, voice, expiry, and supersession controls attached.",
    url: "https://adamcagle.com/canon/",
    tags: ["Creative", "Brand", "AI Operations", "Compliance", "Knowledge"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "RAG", "Evidence graphs", "SHA-256 provenance", "MCP", "Entitlements", "Human approval"],
    presentation: "Canon gives a brand one governed place to speak from. It turns laboratory reports, legal records, product evidence, research, and approved work into substantiated claims with exact source bindings. Claims carry market, product, channel, voice, and expiry rules. Unsupported implications are blocked, conflicts go to accountable owners, and every use creates a receipt that can be recalled if the evidence changes.",
  },
  {
    id: "backlot",
    title: "Backlot",
    kind: "workflow",
    group: "Creative Suite",
    kicker: "Governed AI assisted campaign production",
    headline: "Concept to channel masters, with direction intact.",
    summary: "Turns an approved campaign brief into territories, boards, moving image, voice, score, finished edits, and channel masters under continuity, rights, safety, and human direction.",
    caseStudy: "A boutique desert resort produces a thirty second hero film and five channel masters with property, talent, product, palette, and camera language preserved.",
    url: "https://adamcagle.com/backlot/",
    tags: ["Creative", "Brand", "Hospitality", "Production", "Video", "AI Operations"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Image generation", "Video generation", "Voice generation", "Continuity checks", "EDL assembly", "Rights metadata"],
    presentation: "Backlot turns an approved campaign brief into finished channel masters without surrendering creative direction. An asset bible locks the property, talent, product, palette, and camera language. Models are selected by production role, retries are bounded, and independent checks protect continuity and safety. People choose the territory, takes, grade, mix, and final release. Every master ships with its rights record and production lineage.",
  },
  {
    id: "proving-ground",
    title: "Proving Ground",
    kind: "workflow",
    group: "Fintech and Enterprise",
    kicker: "AI evaluation and release governance",
    headline: "Measure the change. Then decide.",
    summary: "Tests every proposed AI configuration against a governed test set, calibrated independent judges, a pinned production baseline, and explicit release standards.",
    caseStudy: "A records assistant clears safety but fails a groundedness floor on one adjudicated case, giving engineering an exact reproducible failure to correct.",
    url: "https://adamcagle.com/proving-ground/",
    tags: ["Fintech", "Financial", "AI Operations", "Evaluation", "Governance", "Risk"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Model diversity", "Golden sets", "Calibrated judges", "Red teaming", "SHA-256 provenance", "Human adjudication"],
    presentation: "Proving Ground tells a team whether an AI change is actually better before it ships. Every candidate runs against a governed golden set and the current production configuration. Independent model families judge the results only after calibration against human ratings. Safety and quality have separate release floors. If the candidate fails, engineering receives the exact case, scores, rationale, and evidence needed to correct it and test again.",
  },
  {
    id: "field-kit",
    title: "Field Kit",
    kind: "workflow",
    group: "Fintech and Enterprise",
    kicker: "Discovery to working prototype",
    headline: "Find the pain. Price it. Build the proof.",
    summary: "Converts recorded discovery and real customer artifacts into a cited process map, a costed opportunity, a verified read only prototype, and an approved pilot plan.",
    caseStudy: "A regulated fintech maps a two day campaign approval handoff across Slack, spreadsheets, compliance, and its CRM, then approves a fourteen day shadow pilot.",
    url: "https://adamcagle.com/field-kit/",
    tags: ["Fintech", "Financial", "AI Operations", "Discovery", "Product", "Growth"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Speech and vision models", "OCR", "Embeddings", "Evidence linked RAG", "Sandbox verification", "Read only credentials"],
    presentation: "Field Kit is the system behind an embedded AI engagement. It reads a consented discovery call and the artifacts a team actually uses, reconstructs the real process with every claim linked to evidence, and asks the customer to resolve what the sources cannot. It prices the opportunity with honest ranges, builds a read only prototype, verifies it in a sandbox, and delivers an approved shadow pilot that can begin the following week.",
  },
  {
    id: "switchboard",
    title: "Switchboard",
    kind: "workflow",
    group: "Fintech and Enterprise",
    kicker: "Task based model routing and cost governance",
    headline: "The right model for every request, with the receipt attached.",
    summary: "Selects models by task policy, enforces privacy before transport, validates every result, bounds repair, and attributes every attempt and tenth of a cent.",
    caseStudy: "A support summary routes to the least expensive qualified model, completes one alternate family repair, and returns valid, cited output for one point four cents.",
    url: "https://adamcagle.com/switchboard/",
    tags: ["Fintech", "Financial", "AI Operations", "Infrastructure", "Cost", "Privacy"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["OpenRouter", "Model registry", "JSON Schema", "Privacy routing", "Cache policy", "Telemetry", "Cost ledger"],
    presentation: "Switchboard is the routing and cost layer for production AI. Applications describe the task, schema, sensitivity, latency, and quality floor without naming a model. The registry chooses the least expensive qualified route, privacy rules run before transport, and every result is checked against observable evidence. Repair is bounded and uses an alternate model family. The answer returns with a complete trace of quality, latency, and cost.",
  },
  {
    id: "reading-room",
    title: "Reading Room",
    kind: "workflow",
    group: "Fintech and Enterprise",
    kicker: "Enterprise knowledge retrieval",
    headline: "Grounded answers from governed sources.",
    summary: "Answers from owned and current sources with sentence level verification, entitlement before retrieval, and accountable handoff when the evidence cannot settle the question.",
    caseStudy: "A bank support question spans conflicting policy and operations documents, routes to an owner, and becomes a new approved procedure the system can cite next time.",
    url: "https://adamcagle.com/reading-room/",
    tags: ["Fintech", "Financial", "AI Operations", "Knowledge", "RAG", "Compliance"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["MCP", "Hybrid retrieval", "Vector embeddings", "Reranking", "Entitlements", "Sentence verification", "Source governance"],
    presentation: "Reading Room is an enterprise knowledge system that answers from owned, current sources with citations. Entitlements filter the corpus before retrieval, so unauthorized passages never reach the model. Retrieved content is evidence, not instruction. An independent family verifies every factual sentence. Questions the evidence cannot settle go to an accountable person with the complete trace, then become approved articles that improve coverage over time.",
  },
  {
    id: "answer-field",
    title: "Answer Field",
    kind: "workflow",
    group: "Fintech and Enterprise",
    kicker: "Answer engine visibility and audience intelligence",
    headline: "Measure the answers. Map the sources shaping them.",
    summary: "Measures how AI answer engines describe a brand, quantifies uncertainty, identifies influential publishers, and ranks the content and partnership gaps worth acting on.",
    caseStudy: "An independent Los Angeles hotel receives a visibility profile, confidence bands, a map of twenty nine influential publishers, and one prioritized opportunity.",
    url: "https://adamcagle.com/answer-field/",
    tags: ["Hospitality", "Brand", "Creative", "AI Operations", "Research", "AIO", "Growth"],
    languages: ["JavaScript", "HTML", "CSS", "JSON"],
    technology: ["Multi-engine sampling", "OpenRouter", "Embeddings", "Citation graphs", "Confidence intervals", "Canonical URL resolution", "Read only analysis"],
    presentation: "Answer Field measures how AI answer engines describe a brand, to whom, and on whose authority. It freezes a versioned set of real audience questions, samples multiple engines from multiple markets, and reports recommendation rates with confidence bands. A citation graph reveals the publishers shaping the category. The system then compares that external evidence with the brand's own content and ranks the gap worth addressing first.",
  },
  {
    id: "legacy-content-migrator",
    title: "Legacy Content Migrator",
    kind: "workflow",
    group: "Transformation",
    kicker: "Governed content migration",
    headline: "Move the evidence. Keep human authority.",
    summary: "Routes mixed legacy pages, scans, duplicates, conflicts, and recommendations through controlled intake, extraction, evidence matching, independent verification, authority gates, and final audit output.",
    caseStudy: "Three guided cases demonstrate forty executing nodes and forty five evidence carrying connections, with human authority over consequential decisions and zero public writes.",
    url: "https://adamcagle.com/migration_new/",
    tags: ["AI Operations", "Migration", "Knowledge", "Brand", "Content", "Compliance"],
    languages: ["JavaScript", "HTML", "CSS"],
    technology: ["n8n", "OpenRouter", "OCR", "Embeddings", "Evidence IDs", "Deterministic validation", "Independent verification", "Three.js"],
    presentation: "Legacy Content Migrator handles the mess that makes real website migrations dangerous: current pages, old documents, scans, duplicates, conflicts, and recommendations that need accountable review. Every record moves through deterministic intake, extraction, retrieval, evidence matching, independent verification, authority gates, and human decisions. The output is a complete audit record, and the workflow performs no automatic public writes.",
  },
];

export const aiSkills = [
  {
    word: "TONE",
    kicker: "Agency copy tool in action",
    title: "Sunset Marquis Copy System",
    description: "The working voice system Agency689 uses for Sunset Marquis. It carries the speaker, brand pillars, fact rules, banned moves, examples, and channel guidance that keep AI assisted copy accurate and recognizably theirs.",
    viewUrl: "/skills/sm-tone.html",
    downloadUrl: "/skills/SMTONE.md",
    downloadLabel: "Download MD",
  },
  {
    word: "AIC",
    kicker: "Operating system for company design",
    title: "AIC: The AI Corporation",
    description: "A practical playbook for designing an AI native company: mission, agent fleet, workflow interfaces, dashboards, governance, unit economics, and the human decisions that hold the system together.",
    viewUrl: "/skills/aic.html",
    downloadUrl: "/skills/AI_Corporation_SKILL.md",
    downloadLabel: "Download MD",
  },
  {
    word: "GRANTS",
    kicker: "Evidence disciplined proposal building",
    title: "Grant Application Builder",
    description: "A funder focused system for fit analysis, evidence labels, reconciled budgets, portal ready answers, and human review. It accelerates the work without inventing claims or submitting on anyone's behalf.",
    viewUrl: "/skills/grant-application-builder.html",
    downloadUrl: "/skills/grant-application-builder.skill",
    downloadLabel: "Download Skill",
  },
  {
    word: "FINISHER",
    kicker: "Production readiness and ship discipline",
    title: "FINISHER",
    description: "The current production readiness system audits launch risk across security, data, reliability, accessibility, cost, AI safety, testing, and handoff. It turns a working prototype into a product that can be defended in production.",
    viewUrl: "/skills/finisher/FINISHER-complete.md",
    downloadUrl: "/skills/finisher/FINISHER-for-ChatGPT.zip",
    downloadLabel: "Download Current Kit",
  },
];

export const supportingAiCards = [
  { title: "Single Stock Intelligence", label: "Market intelligence and decision support", description: "VRT2 and CLAW organize market, company, supply chain, filings, analyst, and macro evidence into testable hypotheses. Signals move through verification states, weak ideas lose weight, and a kill switch protects the human decision maker from false confidence.", tech: ["Node.js", "Python", "SQLite", "Finnhub", "EDGAR"] },
  { title: "Agent Exchange", label: "Agent commerce architecture", description: "A marketplace architecture where verified agents can publish permitted inventory, discover services, negotiate offers, and build reputation through machine readable interfaces. Identity, policy, disputes, and bounded authority are part of the product rather than an afterthought.", tech: ["Node.js", "PostgreSQL", "MCP", "Ed25519", "OpenAPI"] },
  { title: "BookLite", label: "Governed book marketing", description: "One book, one author voice, and a coordinated system for platform native marketing across major channels. Attribution learning informs the next cycle while a person remains between generated work and public publishing.", tech: ["Claude Agent SDK", "Node.js", "Platform APIs", "Attribution"] },
  { title: "AuScan", label: "Satellite prospectivity research", description: "A vision based research prototype that compares multi sensor satellite imagery with the signatures of known gold deposits, then checks its strongest candidates against USGS records.", tech: ["React", "Claude Vision", "NASA EMIT", "Landsat", "USGS"] },
  { title: "Donkey on the Edge", label: "AI accelerated first principles research", description: "A single sustained learning thread that moved from basic mechanics to a research paper in quantum gravity, preserving the references, wrong turns, curriculum, and reasoning trail along the way.", tech: ["Claude", "Astro", "Markdown", "LaTeX", "Research"] },
  { title: "Book and Music Marketing", label: "Closed loop promotion systems", description: "Multi title and multi artist marketing systems that create channel appropriate work, hold it for approval, track sales or streams, and change the next cycle according to evidence.", tech: ["Platform APIs", "Attribution", "Approval queues"] },
  { title: "Persona Governance", label: "Identity and voice controls", description: "Structured persona specifications that define voice, boundaries, source authority, prohibited behavior, and the moments when an AI must defer to a person. The system supports durable brand personas without pretending consistency is the same thing as judgment.", tech: ["Markdown", "Skill files", "Voice systems", "Human review"] },
  { title: "COOK", label: "Cross market anomaly correlation", description: "A multi asset anomaly engine that turns complicated signal relationships into a dashboard a person can use. The aim is better informed judgment, never an automated financial decision.", tech: ["Signal processing", "Dashboards", "Decision support"] },
];
