import { figueroaBookPages } from "@/content/figueroa-book";

export type CopyCase = {
  id: string;
  client: string;
  category: string;
  headline: string;
  resultLead: string;
  overview: string;
  presentation: string;
  context: string;
  problem: string;
  insight: string;
  system: string;
  outcome: string;
  why: string;
  lines: string[];
  pullQuote?: string;
  pullBody?: string;
  tags: string[];
  industries: string[];
  channels: string[];
  images: { src: string; alt: string; caption: string; description?: string }[];
};

export const copyCases: CopyCase[] = [
  {
    id: "killer",
    client: "Killer Network",
    category: "Brand launch and campaign",
    headline: "WINNING IS KILLER.",
    resultLead: "Zero to Qualcomm in three years.",
    overview: "A complete gaming hardware brand built around the enemy every player already hated: lag. Positioning, naming, packaging, campaigns, partnerships, channel, trade show, web, and television all worked as one launch system.",
    presentation: "Killer Network is the cleanest expression of how Adam turns technical advantage into human motivation. The product was a network card, but the audience did not want networking hardware. Gamers wanted lag dead and the win back in their hands. Adam built the brand around that enemy, then carried Winning is Killer and Less Lag, More Frag through naming, packaging, advertising, web, channel, trade shows, television, and a Blizzard partnership. The company went from incorporation to acquisition by Qualcomm in three years. The lesson is simple: the technology can be complicated. The reason to care cannot be.",
    context: "The world's first network interface card built for online gamers. Brand, positioning, naming, packaging, web, advertising, channel, trade show, and television, written, designed, and shipped from end to end. The work included a Blizzard partnership and a commemorative World of Warcraft coin still collected today.",
    problem: "A gaming networking brand needed to explain a technical performance advantage in a way gamers would actually care about. Hardware specifications were not enough. Lag was the enemy, and the brand had to make that personal.",
    insight: "Gamers do not want networking hardware. They want the lag gone, the game smooth, and the win within reach. The product was permission to stop losing to the connection.",
    system: "Brand positioning, campaign strategy, product naming, product messaging, web copy, advertising, packaging, heat sink design, channel marketing, trade show presence, television spots, and launch support.",
    outcome: "Zero to Qualcomm acquisition in three years.",
    why: "Product marketing at its cleanest: turn technical differentiation into human motivation. The same challenge lives inside every AI, SaaS, and hardware launch today.",
    lines: ["Winning is Killer.", "Less Lag. More Frag.", "End Lag Now."],
    pullQuote: "Less lag. More frag.",
    pullBody: "Three ads, three character classes, and three color coded palettes. Each execution escalated a verb stack into the same two word punchline.",
    tags: ["Brand Launch", "Naming", "Campaign", "Packaging", "Channel"],
    industries: ["Technology", "Gaming", "Consumer"],
    channels: ["Print", "Web", "Packaging", "Trade Show", "Television"],
    images: [
      { src: "/copywriting/killer-warrior.webp", alt: "Killer NIC Warrior gaming print ad", caption: "Warrior. Kill Faster." },
      { src: "/copywriting/killer-mage.webp", alt: "Killer NIC Mage gaming print ad", caption: "Mage. Kill Faster." },
      { src: "/copywriting/killer-sniper.webp", alt: "Killer NIC Sniper gaming print ad", caption: "Sniper. Kill Faster." },
    ],
  },
  {
    id: "traveler",
    client: "Traveler Guitar",
    category: "Brand platform and campaign",
    headline: "THE WORLD'S MOST ADVENTUROUS GUITARS.",
    resultLead: "DTC revenue grew from $1.1M to $5M.",
    overview: "A durable brand platform built on what the product makes possible, not merely what it weighs. The same promise carried products, commerce, retail, advertising, Amazon, and trade shows through sustained growth.",
    presentation: "Traveler Guitar proves the difference between a product feature and a brand platform. Smaller was true, but it was not the story. The product gave musicians permission to take the instrument farther, so Adam built the brand around The World's Most Adventurous Guitars. That promise stretched across product pages, campaigns, email, Amazon, retail, dealer materials, and six trade show environments without wearing out. During the broader engagement, direct-to-consumer revenue grew from roughly 1.1 million dollars to 5 million across Shopify and Amazon while the company protected its independent dealer relationships. One useful truth did the work of years of disconnected taglines.",
    context: "A campaign system built around one promise: a Traveler goes where a regular guitar cannot. One tagline and one visual grammar carried eight executions across campfires, subways, storm fronts, jungles, jet streams, and the open road. Agency689 has been at the helm for more than fifteen years.",
    problem: "A portable guitar brand needed a platform that could hold across products, players, retail, Amazon, trade shows, and advertising over years of growth. It needed more than a tagline. It needed a brand truth.",
    insight: "The product is not just smaller. It gives musicians permission to take the instrument farther. Adventure is the brand, not portability.",
    system: "Brand positioning, product copy, advertising, web copy, Amazon Store consulting, six NAMM trade show booths, print and promotional campaigns, dealer presentations, and speaker decks over more than fifteen years.",
    outcome: "The line became a registered trademark. During the broader engagement, direct-to-consumer revenue grew from roughly $1.1 million to $5 million across Shopify and Amazon while the company protected its independent dealer relationships.",
    why: "A strong product line becomes a brand system when it is elastic enough to carry campaigns, commerce, and community.",
    lines: ["Sonic Bloom.", "Hey Jungle, Welcome to Me.", "Next Stop, Greatness.", "A Force of Nature.", "Flying Solo.", "Endless Strummer."],
    pullQuote: "Willie could not wait to get back on it. Roger was the king of it. And Sheryl found it winding every day.",
    pullBody: "For more than twenty five years, Traveler Guitar has made instruments that fit in tiny spaces, play with giant sound, and let musicians practice, play, or record wherever the road takes them.",
    tags: ["Brand Platform", "Campaign", "Product Copy", "Registered Trademark", "Long Term Growth"],
    industries: ["Consumer", "Music", "Retail"],
    channels: ["Print", "Web", "Amazon", "Trade Show", "Dealer"],
    images: [
      { src: "/copywriting/traveler-jealousy.webp", alt: "Traveler Guitar campfire print campaign", caption: "Making drummers jealous around campfires since 1992." },
      { src: "/copywriting/traveler-sonic-bloom.webp", alt: "Traveler Guitar Sonic Bloom campaign", caption: "Sonic Bloom." },
      { src: "/copywriting/traveler-jungle.webp", alt: "Traveler Guitar jungle campaign", caption: "Hey Jungle, Welcome to Me." },
      { src: "/copywriting/traveler-greatness.jpg", alt: "Traveler Guitar subway campaign", caption: "Next Stop, Greatness." },
      { src: "/copywriting/traveler-force.webp", alt: "Traveler Guitar storm campaign", caption: "A Force of Nature." },
      { src: "/copywriting/traveler-flying-solo.webp", alt: "Traveler Guitar cockpit campaign", caption: "Flying Solo." },
      { src: "/copywriting/traveler-endless-strummer.webp", alt: "Traveler Guitar surf campaign", caption: "Endless Strummer." },
      { src: "/copywriting/traveler-road.webp", alt: "Traveler Guitar open road print ad", caption: "The Road." },
    ],
  },
  {
    id: "sunset",
    client: "Sunset Marquis",
    category: "Brand system and Agency of Record",
    headline: "LEGENDARY NIGHTS BEGIN AT SUNSET.",
    resultLead: "Roughly $150K revenue per email.",
    overview: "More than two decades building one unmistakable voice across rooms, food, music, wellness, events, offers, and a family of hospitality brands without sanding away what made the property legendary.",
    presentation: "Sunset Marquis is Adam's best proof that brand voice can be an operating system. For more than twenty years, the assignment has ranged from rooms and restaurant offers to concerts, spa, art, email, web, and out of home. Legendary Nights Begin at Sunset became the line every part of that world could ladder up to. The email program produces roughly one hundred fifty thousand dollars in attributed revenue per email, and performance-led banner iteration lifted return on ad spend by thirty percent. Adam later moved the judgment behind the voice into a governed copy file so designers could produce stronger first drafts without turning the property generic. The judgment lives in the system, and a person still owns the final line.",
    context: "West Hollywood's rock and roll hotel. Campaigns, web, print, out of home, email, and in room work, plus the sub brands Cavatina, LIVE@SunsetMarquis, Bar 1200, The Spa, and The Morrison Gallery. Home away from home for rock stars, road dogs, and the occasional free radical.",
    problem: "A storied independent hotel had to grow without becoming ordinary. Every room offer, restaurant menu, concert announcement, trade sheet, and email needed to sell while belonging to the same unmistakable world.",
    insight: "The luxury is access without exposure. Sunset Marquis is both a sanctuary and part of music history, so the voice can be elegant, knowing, and willing to wink without ever trying too hard.",
    system: "Brand voice, campaign platform, web, print, out of home, email, in room collateral, restaurant language, concert series naming, and governance across a family of property brands.",
    outcome: "Agency of Record since 2004, a Netty Award winning website, roughly $150,000 average revenue attributed per email, and a 30 percent lift in banner return on ad spend.",
    why: "This is voice as an operating system. One character can sell rooms, food, music, wellness, and events for decades without flattening into a formula.",
    lines: ["Legendary Nights Begin at Sunset.", "Yes, that beautiful.", "Sure, it is California, but it is the southern part.", "Unique. Even by Hollywood standards."],
    pullQuote: "Legendary nights begin at Sunset.",
    pullBody: "Ten years on the door, the print, the email, and the sign off. It is the line the rest of the brand ladders up to.",
    tags: ["Brand Voice", "Campaign", "Email", "Web", "Out of Home", "Voice Governance"],
    industries: ["Hospitality", "Entertainment", "Food and Beverage"],
    channels: ["Email", "Print", "Web", "OOH", "In Room"],
    images: [
      { src: "/copywriting/sunset-legendary-nights.webp", alt: "Sunset Marquis Yes That Beautiful print campaign", caption: "Yes, that beautiful." },
      { src: "/copywriting/sunset-yes-that-beautiful.jpg", alt: "Sunset Marquis Legendary Nights campaign", caption: "Legendary Nights Begin at Sunset." },
      { src: "/copywriting/ACM-Awards-2025.jpg", alt: "Sunset Marquis ACM Awards campaign", caption: "Sure, it is California, but it is the southern part." },
      { src: "/copywriting/SMBrochure.jpg", alt: "Sunset Marquis GDS trade sell sheet", caption: "Unique. Even by Hollywood standards." },
      { src: "/copywriting/Sunset-Marquis.jpg", alt: "Sunset Marquis website", caption: "The brand operating in the wild." },
    ],
  },
  {
    id: "figueroa",
    client: "Hotel Figueroa",
    category: "Brand book and editorial voice",
    headline: "TO RELATE TO ARTISTS, WE MUST BE ARTISTS.",
    resultLead: "One idea. A 61-page brand system.",
    overview: "The identity and editorial foundation for a 1925 Los Angeles icon reopening as a luxury hotel for creative minds. One sentence became the test for every visual, verbal, and experiential decision.",
    presentation: "Hotel Figueroa began with one sentence: To relate to artists, we must be artists. Adam used it as a decision rule, not a decorative manifesto. Six brand pillars, the mission, promise, visual identity, typography, imagery direction, collateral, and the complete editorial voice all had to prove that sentence true. The result was a sixty-one-page system that gave a historic Los Angeles hotel a modern creative point of view without erasing its past. This is how Adam works at brand scale: find the sentence that can govern the thousand decisions after it.",
    context: "A full brand identity and editorial system for the 1925 Downtown Los Angeles icon's reopening as a luxury hotel for creative minds. Six brand pillars, mission, promise, vision, signature identity, typography, imagery direction, collateral, and complete editorial voice guidance.",
    problem: "A historic hotel was reopening into a crowded luxury market. It needed a complete identity that respected its story while giving a modern creative audience a reason to claim it.",
    insight: "To earn credibility with creative people, the brand itself had to behave creatively. That sentence became the foundation for every visual, verbal, and experiential decision.",
    system: "Mission, promise, vision, six brand pillars, identity variants, typography, graphic marks, a three tier imagery system, editorial voice, full collateral, and governance through launch.",
    outcome: "A sixty one page brand book and complete editorial and identity system.",
    why: "Brand voice is infrastructure. AI writing systems should extend a governed mission, visual language, editorial standard, and body of evidence, not replace them.",
    lines: ["To relate to artists, we must be artists."],
    pullQuote: "To relate to artists, we must be artists.",
    pullBody: "The single sentence that holds the entire brand. Six pillars and sixty one pages of identity work flow from it.",
    tags: ["Brand Platform", "Identity System", "Voice Guide", "Design System", "Collateral"],
    industries: ["Hospitality", "Arts", "Luxury"],
    channels: ["Brand Book", "Web", "Email", "Trade Show", "Collateral"],
    images: figueroaBookPages.map((src, index) => ({
      src,
      alt: `Hotel Figueroa brand book page ${index + 1} of ${figueroaBookPages.length}`,
      caption: index === 0 ? "Complete 61-page brand book." : `Brand book page ${index + 1}.`,
    })),
  },
  {
    id: "performance",
    client: "Performance Marketing",
    category: "Strategy, email, display, and paid social",
    headline: "MAKE THE BRAND PERFORM.",
    resultLead: "30% lift in banner return on ad spend.",
    overview: "High-volume email, display, and paid social work built as connected conversion paths, not isolated executions. Every campaign had to earn attention, protect the voice, and produce a measurable result.",
    presentation: "Performance copy makes its case in the numbers while keeping the brand worth remembering. Banner, social, and email are different jobs: display has seconds to make one promise clear, social has to earn attention in the feed, and email carries the complete path from subject line to action. Across years of recurring campaign work, that discipline produced a thirty percent lift in banner return on ad spend and roughly one hundred fifty thousand dollars in attributed revenue per Sunset Marquis email. Volume went up without allowing the brand voice to go flat.",
    context: "For more than a decade, Adam created the strategy and wrote the copy for multiple email, banner, and social campaigns every month across clients and vertical markets. The assignment changes. The discipline does not: find the offer, protect the voice, make the click worth earning, and turn attention into measurable revenue.",
    problem: "High volume performance work can flatten a brand fast. Every campaign still has to sell without sounding like every other promotion in the inbox or feed.",
    insight: "Build the strategy around audience, offer, moment, and channel. Then write the subject line, headline, body copy, call to action, and variants as one connected conversion path.",
    system: "Monthly campaign calendars, concepts, copy platforms, offer framing, channel adaptation, creative direction, testing, iteration, and reporting across email, display, and social.",
    outcome: "A repeatable campaign engine that protects the brand and produces measurable returns, including a 30 percent lift in banner return on ad spend and roughly $150,000 average revenue per Sunset Marquis email.",
    why: "Volume and voice do not have to trade places. The best performance systems create more chances to convert while making the brand more recognizable every time it appears.",
    lines: ["Make the brand perform."],
    pullQuote: "Performance marketing is not where brand voice goes to disappear.",
    pullBody: "Strategy, timing, offer, and language have to work hardest together, month after month and channel after channel, with the numbers keeping score.",
    tags: ["Email", "Display", "Paid Social", "Campaign Strategy", "Conversion Copy", "Testing"],
    industries: ["Performance", "Hospitality", "Consumer", "B2B"],
    channels: ["Email", "Display", "Paid Social"],
    images: [
      { src: "/copywriting/banner-hero.webp", alt: "Banner and display campaigns", caption: "Banner and display campaigns.", description: "Display work compresses audience, offer, idea, and action into a few seconds of attention. Connected campaign variants can test the strongest promise without making the brand look or sound disposable." },
      { src: "/copywriting/email-mockup.webp", alt: "Sunset Marquis email campaigns", caption: "$150K average revenue per email.", description: "Email carries the complete conversion path: subject line, opening idea, offer, proof, and action. Sunset Marquis campaigns average roughly $150,000 in attributed revenue per email." },
      { src: "/copywriting/social-mockup.webp", alt: "Sunset Marquis social campaigns", caption: "Always on brand storytelling.", description: "Paid and organic social adapt the campaign idea to the feed rather than shrinking a banner. The visual hook, message hierarchy, and voice change with the placement while the brand remains recognizable." },
    ],
  },
  {
    id: "clink",
    client: "Clink Hostels",
    category: "International brand voice and website copy",
    headline: "MEASURE YOUR JOURNEY IN FRIENDS, NOT MILES.",
    resultLead: "One voice across four European cities.",
    overview: "A complete website and messaging architecture for an international hostel brand. The voice scales across cities, properties, groups, offers, and travel guidance while keeping human connection at the center.",
    presentation: "Clink Hostels needed one voice to travel across different properties, cities, offers, groups, and audience needs. Adam found the human center of the category: a hostel is not merely a cheaper bed. The people you meet can become the reason you went. Measure your journey in friends, not miles turned that belief into a usable messaging architecture across nine production website screens and four European cities. The work shows how a voice system can scale geographically without sounding like it came from a franchise template.",
    context: "Full website copy and messaging architecture for an international hostel brand with properties in London, Amsterdam, Dublin, and beyond. The voice positions Clink as the hostel for people who travel to connect, not just to arrive.",
    problem: "One international brand needed to speak across properties, offers, groups, city guides, geographies, and audience cohorts without turning into generic travel copy.",
    insight: "A hostel is not a bed or a budget. It is a place where the people you meet become the reason you went.",
    system: "Brand voice, messaging architecture, homepage, property pages, groups, offers, and city guides, held in one warm, irreverent, and quietly aspirational voice.",
    outcome: "A complete international brand voice and nine production website screens across four European cities.",
    why: "Proof that a voice system can scale across geographies, audiences, properties, and channel formats while remaining recognizably itself.",
    lines: ["Measure your journey in friends, not miles."],
    pullQuote: "Measure your journey in friends, not miles.",
    pullBody: "The line reframes what a hostel is for. The people you meet become the reason you went.",
    tags: ["Brand Voice", "Messaging Architecture", "Website Copy", "International", "Hospitality"],
    industries: ["Hospitality", "Travel", "Consumer"],
    channels: ["Web", "Property Pages", "Offers", "City Guides"],
    images: [{ src: "/copywriting/clink-amsterdam.jpg", alt: "Clink Hostels Amsterdam website", caption: "One brand voice across four European cities." }],
  },
  {
    id: "filekeepers",
    client: "FileKeepers",
    category: "Rebrand and vertical campaign",
    headline: "SPACE. THE FILE FRONTIER.",
    resultLead: "5% annual growth in target verticals.",
    overview: "A records-management rebrand that stopped selling boxes and started selling the useful future on the other side of them. Research identified space as the real customer motivation, then the campaign made it visible.",
    presentation: "FileKeepers sold records management, a necessary service in a category nobody was excited to discuss. Research revealed the actual purchase motive: space. Adam stopped selling storage and started showing what a business could do with the room it got back. Space, The File Frontier turned emptied offices into the campaign, then extended through a rebrand, photography, vehicles, sales materials, and vertical work for legal, healthcare, and financial clients. New-client growth reached five percent in the targeted verticals. The feature was boxes. The idea was possibility.",
    context: "Records management is not a glamorous category. Nobody wakes up excited about bar codes and certified shredding. What they do get excited about is the empty room. The campaign stopped selling storage and started selling what comes after it.",
    problem: "A records management company serving seven of the top ten law firms in Southern California needed to stand out in a category most people viewed as boxes and logistics. Operational necessity is not a brand.",
    insight: "Research confirmed that the number one reason businesses hire a records management company is space. Physical, useful, reimagined office space.",
    system: "Logo, full rebrand, campaign copy, photography direction, vehicle graphics, sales materials, trade advertising, and vertical marketing for law firms, healthcare, and financial services.",
    outcome: "Five percent year over year growth in new clients across targeted verticals and four percent growth overall.",
    why: "Many SaaS brands have the same problem. The feature may be operational, but the buyer is looking for a more useful future. The line is the bridge.",
    lines: ["Space. The File Frontier."],
    pullQuote: "Stop selling storage. Start selling possibility.",
    pullBody: "Four recently emptied rooms, four characters, one log entry, and one line. The brief changed the moment the real customer motivation became clear.",
    tags: ["B2B", "Rebrand", "Concept", "Strategy", "Print", "Art Direction"],
    industries: ["B2B", "Financial", "Legal", "Healthcare"],
    channels: ["Print", "Vehicle", "Sales", "Trade"],
    images: [
      { src: "/copywriting/FileKeepers_SPACE1.jpg", alt: "FileKeepers empty office campaign one", caption: "Space. Room one." },
      { src: "/copywriting/FileKeepers_SPACE12.jpg", alt: "FileKeepers empty office campaign two", caption: "Space. Room two." },
      { src: "/copywriting/FileKeepers_SPACE13.jpg", alt: "FileKeepers empty office campaign three", caption: "Space. Room three." },
      { src: "/copywriting/FileKeepers_SPACE14.jpg", alt: "FileKeepers empty office campaign four", caption: "Space. Room four." },
    ],
  },
  {
    id: "navis",
    client: "NAVIS",
    category: "B2B SaaS positioning, campaign, and naming",
    headline: "CRM BECAME GRM.",
    resultLead: "A category NAVIS could own.",
    overview: "NAVIS had built more than another customer relationship management platform. Renaming CRM as GRM, Guest Relationship Management, turned its real difference into a category the company could own.",
    presentation: "NAVIS had built more than another customer relationship management platform. Its software connected data, reservation sales, marketing, and human follow-up around the guest relationship. Adam gave that difference a name: G R M, Guest Relationship Management. The new category moved NAVIS out of the generic C R M comparison set and made its promise clear in three letters. Campaign lines including The Phone Is Mightier Than The Mouse supplied the proof, backed by a forty-six percent phone conversion rate versus roughly two percent online. But the bigger win was the name. C R M described the software. G R M described why hospitality companies needed it.",
    context: "NAVIS combined hospitality data, reservation sales, marketing, and human follow-up in one platform. Rather than compete as another CRM, it needed language that made its guest-centered difference unmistakable. NAVIS was acquired by Revinate in 2021.",
    problem: "CRM put NAVIS in a generic software category and made the product sound like a database. The name did not capture the human relationship, revenue performance, or hospitality expertise that made the platform different.",
    insight: "Hotels do not manage customers. They build relationships with guests. Changing one letter moved the product from a software description to a hospitality promise.",
    system: "Category naming, positioning, campaign strategy, headlines, body copy, print, and dedicated landing pages all organized around GRM. Conversion data and the reservation team supplied the proof behind the new category.",
    outcome: "GRM gave NAVIS a category it could lead, supported its position in hospitality reservation sales, and remained central to the brand story through its acquisition by Revinate in 2021.",
    why: "Category naming changes the comparison. CRM made NAVIS one platform among many. GRM made the guest relationship the standard competitors had to answer.",
    lines: ["GRM. Guest Relationship Management.", "The phone is mightier than the mouse.", "Traffic does not make reservations. Guests do.", "Hospitality is not an automated process."],
    pullQuote: "CRM DESCRIBED THE SOFTWARE. GRM DESCRIBED THE BUSINESS.",
    pullBody: "One changed letter gave the platform a human center of gravity and NAVIS a category it could own. The campaign then proved the idea with performance, profit, and a guaranteed return on investment.",
    tags: ["Positioning", "Campaign", "Naming", "B2B", "SaaS", "Print"],
    industries: ["Hospitality", "Technology", "B2B"],
    channels: ["Print", "Landing Pages", "Sales"],
    images: [
      { src: "/copywriting/navis-grm.jpg", alt: "NAVIS GRM campaign", caption: "GRM. Guest Relationship Management." },
      { src: "/copywriting/navis-mightier.jpg", alt: "NAVIS phone versus web campaign", caption: "The phone is mightier than the mouse." },
      { src: "/copywriting/navis-most-powerful.jpg", alt: "NAVIS most powerful booking engine campaign", caption: "The most powerful booking engine in the world." },
      { src: "/copywriting/navis-traffic.jpg", alt: "NAVIS traffic campaign", caption: "Traffic does not make reservations. Guests do." },
    ],
  },
];
