window.WORKFLOW_CONFIG={
  title:'Field Kit',kicker:'Discovery-to-prototype engine',
  headline:'Turn discovery into something runnable.',
  intro:'Follow one operating pain point from a recorded call and messy customer artifacts to a cited process graph, a costed backlog, and a read-only prototype.',
  stages:['Source intake','Normalize','Evidence graph','Ambiguity','Scope gate','Opportunity','Prototype','Engagement packet'],
  case:{id:'FD-017',type:'ONE GUIDED DISCOVERY',title:'Fintech campaign approval handoff',summary:'A growth team loses two days moving regulated campaign copy between Slack, spreadsheets, compliance, and its CRM.',route:'Discovery · approved prototype',cardLabel:'Discovery case',cardSub:'Fintech ops',cta:'Map the opportunity'},
  nodes:[
    {id:'sources',stage:0,lane:0,kind:'input',label:'Call + customer artifacts',summary:'Consented audio, Slack exports, screenshots, SOPs, and a handoff spreadsheet enter one evidence envelope.',decision:'Accept five source artifacts and preserve provenance.',why:'The real workflow lives across conversation and tool residue, not in one polished requirements document.',narration:'We start with a discovery call and the artifacts the customer actually uses: Slack, screenshots, an SOP, and a spreadsheet tracking compliance handoffs.'},
    {id:'consent',stage:0,lane:1.25,kind:'gate',label:'GATE · Consent + scope',summary:'Source permissions, retention, tenant, and sensitive-data rules are checked before model calls.',decision:'PASS for this consented, synthetic demonstration.',why:'Discovery data can contain customer and employee information that must not drift across tenants.',narration:'Before any model sees the material, deterministic checks confirm consent, retention, tenant boundaries, and the demo’s synthetic-data status.'},
    {id:'normalize',stage:1,lane:0,kind:'model',tier:'OPENROUTER · MULTIMODAL',label:'Diarize + multimodal extract',summary:'Speech turns, OCR, table structure, and UI text become normalized chunks with timestamps and source coordinates.',decision:'Create 186 attributed evidence chunks.',why:'Every later process claim needs a path back to what a person said or what an artifact showed.',narration:'Task routing chooses speech and multimodal models for recall-heavy extraction. Timestamps, speakers, page numbers, and screen regions remain attached.'},
    {id:'router',stage:1,lane:-1.25,kind:'code',label:'OpenRouter task registry',summary:'Speech, vision, extraction, reasoning, and writing tasks each receive a model that clears their quality and privacy floor.',decision:'Use inexpensive extraction models; reserve deep reasoning for graph synthesis.',why:'The expensive model should solve the hard integration problem, not transcribe every cell.',narration:'OpenRouter selection is task-based. Cheap models handle structured recall, while the long-context reasoning budget is saved for reconstructing the process.'},
    {id:'entities',stage:2,lane:-.8,kind:'model',tier:'OPENROUTER · SMALL',label:'Entity + metric extraction',summary:'A schema captures actors, systems, artifacts, decisions, volumes, wait times, errors, and confidence ranges.',decision:'Identify nine systems, six roles, and a 1.4-to-2.2-day approval wait.',why:'The workflow needs typed facts, including uncertainty, before it can become a graph or cost model.',narration:'A schema-first extraction names every actor, system, queue, volume, and delay. Vague numbers remain ranges instead of becoming invented precision.'},
    {id:'evidence',stage:2,lane:.85,kind:'data',label:'Evidence-linked RAG index',summary:'Each claim receives an EV identifier pointing to a transcript span, screenshot region, or table cell.',decision:'Index 186 chunks and attach citations to every graph node.',why:'A customer must be able to challenge a proposed process step and jump directly to its source.',narration:'The normalized evidence becomes a retrieval index. Every assertion in the process graph cites an EV identifier that opens the exact source span.'},
    {id:'graph',stage:2,lane:0,kind:'model',tier:'OPENROUTER · REASONING',label:'Process-graph synthesis',summary:'A long-context reasoning model creates a typed graph of actors, systems, waits, decisions, rework, and outputs.',decision:'Model a 23-step campaign approval workflow.',why:'This is the one task that must reconcile the entire discovery context at once.',narration:'A reasoning model synthesizes the complete process graph, but it can only use claims supported by the evidence index.'},
    {id:'ambiguity',stage:3,lane:0,kind:'model',tier:'OPENROUTER · ALT FAMILY',label:'Independent ambiguity check',summary:'A second provider family finds graph claims the sources never actually settled.',decision:'Flag the CRM write-back owner and the legal exception path.',why:'The synthesis model should not audit its own confident assumptions.',narration:'A different model family inspects the graph against the same evidence and finds two unresolved claims the synthesis model treated as settled.'},
    {id:'scope',stage:4,lane:0,kind:'human',label:'GATE · Human scope',summary:'A human resolves flagged nodes and chooses the subgraph that is safe and valuable to prototype.',decision:'Prototype approval-status preparation; exclude CRM writes and legal exceptions.',why:'Scope and operational authority belong to the customer and implementation lead.',narration:'The customer confirms the safe slice: automate evidence preparation and status summaries, but leave CRM writes and legal exceptions outside the prototype.'},
    {id:'parameters',stage:5,lane:-.75,kind:'model',tier:'OPENROUTER · SMALL',label:'Score parameters',summary:'Volumes, handle times, error costs, determinism, and blast radius are extracted with confidence intervals.',decision:'Use ranges for missing labor and rework data.',why:'The cost model should expose uncertainty instead of manufacturing a single payback number.',narration:'A small extraction model assembles the scorer inputs and preserves uncertainty wherever discovery did not establish a point estimate.'},
    {id:'score',stage:5,lane:.1,kind:'code',label:'Opportunity + COGS scorer',summary:'Deterministic formulas combine time, volume, error cost, data readiness, risk, and inference cost.',decision:'Rank approval-status preparation first with a 2.4-to-4.1-month payback band.',why:'The recommendation must survive scrutiny from finance and security, not merely sound exciting.',narration:'Code—not a model—calculates opportunity, monthly inference cost, and a payback range. The approval handoff ranks first because it is frequent, bounded, and read-only.'},
    {id:'backlog',stage:5,lane:1.25,kind:'human',label:'GATE · Backlog approval',summary:'The implementation lead can accept, reorder, or kill machine-ranked opportunities.',decision:'Approve FD-017 as the prototype slice.',why:'Repeated human reorderings become calibration data for the scorer.',narration:'A human approves this backlog item. Any reordering is logged so the opportunity formula can be improved instead of quietly ignored.'},
    {id:'scaffold',stage:6,lane:-.7,kind:'model',tier:'OPENROUTER · FRONTIER',label:'Runnable scaffold generation',summary:'Tool-using generation creates read-only connectors, a workflow skill, seeded evals, and one functioning happy path.',decision:'Generate a local prototype with mocked CRM and compliance connectors.',why:'The output should be executable evidence, not another requirements deck.',narration:'A tool-capable frontier model turns the approved slice into a runnable repository with read-only connector stubs and a seeded golden set.'},
    {id:'sandbox',stage:6,lane:.25,kind:'code',label:'Sandbox verification',summary:'The prototype boots in isolation, runs the happy path, and receives one bounded repair if necessary.',decision:'PASS after one dependency correction.',why:'A scaffold that has never run is not a prototype.',narration:'The generated project runs in an isolated sandbox. One deterministic dependency error is repaired, then the complete happy path passes.'},
    {id:'credentials',stage:6,lane:1.2,kind:'gate',label:'GATE · Read-only credentials',summary:'Requested scopes are compared to an allowlist; any write scope is refused by construction.',decision:'PASS with read-only mock scopes and zero customer credentials.',why:'The demo cannot mutate a customer system even if a prompt asks it to.',narration:'The credential gate proves the prototype has no write path. This is enforced in the manifest, not promised in a slide.'},
    {id:'packet',stage:7,lane:0,kind:'output',label:'Cited engagement packet',summary:'The graph, evidence index, approved backlog, cost model, runnable prototype, and shadow-mode plan ship together.',decision:'Deliver the packet for customer review.',why:'Every claim and implementation choice remains traceable to discovery evidence.',narration:'The engagement packet contains the cited graph, costed backlog, runnable prototype, and a shadow-mode pilot plan with owners and kill criteria.'}
  ],
  edges:[['sources','consent'],['consent','router'],['consent','normalize'],['router','normalize'],['normalize','entities'],['normalize','evidence'],['entities','evidence'],['entities','graph'],['evidence','graph'],['graph','ambiguity'],['ambiguity','scope'],['scope','parameters'],['parameters','score'],['score','backlog'],['backlog','scaffold'],['scaffold','sandbox'],['sandbox','credentials'],['credentials','packet'],['evidence','packet','feedback']],
  route:['sources','consent','router','normalize','entities','evidence','graph','ambiguity','scope','parameters','score','backlog','scaffold','sandbox','credentials','packet'],
  completion:{title:'Discovery becomes a safe prototype.',copy:'The system turns messy discovery evidence into a customer-confirmed process map, a costed opportunity, and a runnable read-only prototype without inventing scope or touching production.',proof:'Cited runnable path',human:'Scope + backlog approval',write:'Zero customer writes'}
};
