window.WORKFLOW_CONFIG={
  title:'Answer Field',kicker:'Answer-engine visibility observatory',
  headline:'Measure the answers. Find the sources that shape them.',
  intro:'Follow one commercial-intent query cluster through a frozen dataset, repeated answer-engine probes, independent framing judges, confidence bands, a citation graph, and a read-only SEO handoff.',
  stages:['Query intake','Cluster','Freeze set','Repeated probes','Extract','Frame + variance','Citation graph','Read-only handoff'],
  case:{id:'AF-031',type:'ONE GUIDED QUERY CLUSTER',title:'Best treasury automation platform',summary:'Measure whether a fintech brand appears, how it is framed, and which third-party sources influence the answer across engines and repeated samples.',route:'Comparison cluster · weekly observation',cardLabel:'Query cluster',cardSub:'Answer visibility',cta:'Run the observation'},
  nodes:[
    {id:'queries',stage:0,lane:0,kind:'input',label:'Demand-backed query seeds',summary:'Search Console demand, people-also-ask questions, and clearly tagged synthetic long-tail candidates enter one dataset.',decision:'Start with 37 observed comparison queries and 12 synthetic variants.',why:'Synthetic coverage is useful only when it remains distinguishable from real demand.',narration:'We begin with a comparison cluster anchored in queries people actually used. Synthetic long-tail variants are allowed, but they remain labeled and never inflate historical demand.'},
    {id:'privacy',stage:0,lane:1.25,kind:'gate',label:'GATE · Query privacy',summary:'Tenant isolation and sensitive-query filters run before external probing.',decision:'PASS because the set contains public category language only.',why:'Search data can reveal customer strategy even when it contains no personal information.',narration:'The privacy gate confirms these queries are safe to probe externally and keeps the customer’s private search data isolated.'},
    {id:'cluster',stage:1,lane:0,kind:'code',label:'Intent + buying-stage cluster',summary:'Embeddings and deterministic rules group queries by intent, funnel stage, entity, and geography.',decision:'Assign AF-031 to commercial comparison intent.',why:'Losing comparison queries is a different business problem from losing definitions.',narration:'Embedding similarity groups the queries, then deterministic labels add buying stage and geography. AF zero thirty-one becomes a commercial comparison cluster.'},
    {id:'freeze',stage:2,lane:0,kind:'data',label:'Versioned query set v12',summary:'The normalized set, generation flags, source metadata, and hash are frozen for valid comparisons.',decision:'Freeze 49 queries as version twelve.',why:'Month-over-month movement is only credible when the instrument does not quietly change.',narration:'The query set is versioned and frozen. Future comparisons can add a new version, but they cannot rewrite the history of this one.'},
    {id:'router',stage:2,lane:-1.3,kind:'code',label:'OpenRouter task selector',summary:'High-volume extraction, contested framing, diagnosis, and narrative writing each receive different model routes.',decision:'Use a small extractor, two independent reasoning families, and batch frontier writing.',why:'The observatory spends quality where judgment is contested and keeps high-volume reading economical.',narration:'OpenRouter assigns models by task: cheap structured extraction at volume, independent reasoning families for framing, and frontier batch work only for the weekly narrative.'},
    {id:'schedule',stage:3,lane:0,kind:'code',label:'Repeated probe scheduler',summary:'Each query runs across engines, geographies, and repeated samples with timestamped execution logs.',decision:'Schedule five samples across three engines and two geographies.',why:'Answer-engine outputs are stochastic; one probe cannot support a stable visibility claim.',narration:'The scheduler fans the frozen set across engines, regions, and five repeated samples. Repetition is what turns an anecdote into a measurement.'},
    {id:'engines',stage:3,lane:1.2,kind:'external',label:'Answer engines',summary:'Complete answers, cited URLs, order, timestamps, engine, and geography are captured as raw observations.',decision:'Store the full response before reducing it to metrics.',why:'Raw observations allow later questions without rerunning the historical instrument.',narration:'The engines are instruments, not judges. Their complete answers and citations are stored so the raw evidence remains available.'},
    {id:'extract',stage:4,lane:0,kind:'model',tier:'OPENROUTER · SMALL',label:'Mention + citation extraction',summary:'A schema records presence, position, cited sources, answer spans, and extraction confidence per sample.',decision:'Brand appears in 8 of 30 answers and is recommended in 2.',why:'High-volume structured reading does not require a frontier model.',narration:'A small routed model extracts every mention, its position, and every citation. The brand appears in eight answers but receives only two recommendations.'},
    {id:'judges',stage:5,lane:-.75,kind:'model',tier:'OPENROUTER · 2 FAMILIES',label:'Independent framing judges',summary:'Two blind judges classify each mention as recommended, listed, neutral, dismissed, or disputed and quote evidence.',decision:'Agree that four mentions frame the brand as expensive; disagree on one answer.',why:'Visibility without framing can turn a negative mention into a misleading success metric.',narration:'Two model families judge framing independently. They agree that several mentions position the brand as expensive and preserve one disputed answer for review.'},
    {id:'variance',stage:5,lane:.55,kind:'code',label:'Variance + confidence bands',summary:'Sample spread becomes an interval and cluster volatility score; judge disagreement stays visible.',decision:'Report 27% share of answer with a 19–35% interval and high volatility.',why:'A single percentage conceals the instability decision-makers most need to see.',narration:'Code turns repeated samples into a confidence band. This cluster is volatile, so the report shows a range rather than a false-precision score.'},
    {id:'canonical',stage:6,lane:-1.15,kind:'code',label:'Citation canonicalization',summary:'Redirects, parameters, mirrored domains, and duplicate URLs collapse into stable publisher identities.',decision:'Reduce 74 URLs to 29 canonical publishers.',why:'A source graph should count trusted publishers, not tracking variations.',narration:'Citation URLs are normalized into publisher identities. Seventy-four raw links become twenty-nine canonical sources.'},
    {id:'graph',stage:6,lane:0,kind:'data',label:'Citation influence graph',summary:'Queries, answer engines, claims, publishers, and brand mentions form a traversable evidence graph.',decision:'Identify three publishers that dominate comparison answers.',why:'The actionable question is where engines already obtain trusted evidence.',narration:'The citation graph reveals three third-party publishers that repeatedly shape answers in this cluster. Those relationships matter more than another rewrite of the brand’s homepage.'},
    {id:'diagnose',stage:6,lane:1.2,kind:'model',tier:'OPENROUTER · REASONING',label:'Gap diagnosis',summary:'A reasoning model uses the citation graph, site RAG, schema inventory, and SEO rules to draft specific defects.',decision:'Diagnose missing comparison evidence and weak third-party corroboration.',why:'“Write more content” is not an executable recommendation.',narration:'A reasoning model compares the answer evidence with the site’s retrieved content and schema. It identifies a missing comparison asset and insufficient third-party corroboration.'},
    {id:'score',stage:7,lane:-1.15,kind:'code',label:'Backlog scoring',summary:'Demand, absence, volatility, difficulty, evidence quality, and expected reach determine priority.',decision:'Rank the comparison-evidence ticket first.',why:'Deterministic priority survives preference-driven stakeholder debate.',narration:'The draft tickets are scored with a visible formula. The comparison-evidence gap ranks first because demand is real, absence is high, and the source path is clear.'},
    {id:'readonly',stage:7,lane:0,kind:'gate',label:'GATE · Read-only observatory',summary:'The measurement system holds no website write credentials and can only emit an evidence-linked handoff.',decision:'PASS the backlog to the implementation system.',why:'Measurement should not silently become autonomous optimization.',narration:'The read-only gate prevents this observatory from changing a website. It can measure, diagnose, and hand off—nothing more.'},
    {id:'handoff',stage:7,lane:1.15,kind:'output',label:'Governed SEO handoff',summary:'Tickets, citations, confidence bands, query-set version, and rollback requirements move to an approval-controlled system.',decision:'Queue one evidence-backed ticket for human approval.',why:'Execution belongs in a separate workflow with approval and rollback controls.',narration:'The final packet enters the governed SEO workflow with its evidence, uncertainty, and source graph attached. A human still decides whether any change should happen.'},
    {id:'narrative',stage:7,lane:2.25,kind:'model',tier:'OPENROUTER · FRONTIER BATCH',label:'Weekly narrative',summary:'An overnight model writes the client brief in house voice and leads with what worsened.',decision:'Explain declining recommendation share and rising volatility.',why:'The system should turn measurement into a readable decision brief without hiding bad news.',narration:'A batch model prepares the weekly narrative, explicitly leading with what got worse and linking every claim back to the frozen dataset.'}
  ],
  edges:[['queries','privacy'],['privacy','cluster'],['cluster','freeze'],['freeze','router'],['router','schedule'],['schedule','engines'],['engines','extract'],['extract','judges'],['extract','variance'],['judges','variance'],['variance','canonical'],['canonical','graph'],['graph','diagnose'],['diagnose','score'],['score','readonly'],['readonly','handoff'],['variance','narrative'],['graph','narrative'],['score','narrative']],
  route:['queries','privacy','cluster','freeze','router','schedule','engines','extract','judges','variance','canonical','graph','diagnose','score','readonly','handoff'],
  completion:{title:'Visibility becomes an evidence-backed backlog.',copy:'The observatory measures repeated answers, preserves uncertainty, identifies the publishers shaping the category, and hands one prioritized diagnosis to a separate approval-controlled execution system.',proof:'Frozen set + confidence band',human:'Approves downstream work',write:'Zero observatory writes'}
};
