window.WORKFLOW_CONFIG={
  title:'Answer Field',kicker:'Answer-engine visibility observatory',
  headline:'Measure the answers. Find the sources that shape them.',
  intro:'Follow one travel-discovery audience through observed questions, a frozen intent map, repeated answer-engine probes, independent framing judges, confidence bands, a citation graph, and a read-only growth handoff.',
  stages:['Query intake','Cluster','Freeze set','Repeated probes','Extract','Frame + variance','Citation graph','Read-only handoff'],
  case:{id:'AF-044',type:'ONE GUIDED AUDIENCE STUDY',title:'Los Angeles boutique-hotel discovery',summary:'Learn how travelers frame a creative weekend, which questions signal booking intent, whether an independent hotel enters the answer, and which sources influence the recommendation.',route:'Travel intent · answer visibility',cardLabel:'Audience question set',cardSub:'Hospitality discovery',cta:'Run the study'},
  nodes:[
    {id:'queries',stage:0,lane:0,kind:'input',label:'Demand-backed audience questions',summary:'Search Console demand, site search, booking-path themes, people-also-ask questions, and clearly tagged synthetic long-tail candidates enter one dataset.',decision:'Start with 42 observed travel questions and 14 synthetic coverage probes.',why:'Synthetic coverage is useful only when it remains distinguishable from real audience behavior.',narration:'We begin with questions travelers actually asked about a Los Angeles creative weekend. Synthetic variants can expand coverage, but they stay labeled and never masquerade as demand.'},
    {id:'privacy',stage:0,lane:1.25,kind:'gate',label:'GATE · Query privacy',summary:'Tenant isolation, aggregation, and sensitive-query filters run before external probing.',decision:'PASS public travel language; retain first-party booking terms only as aggregate themes.',why:'Search and booking-path data can reveal guest intent even when it contains no direct identifiers.',narration:'The privacy gate keeps first-party behavior aggregated and sends only public travel language to external answer engines.'},
    {id:'cluster',stage:1,lane:0,kind:'code',label:'Audience intent map',summary:'Embeddings and deterministic rules group questions by trip occasion, neighborhood, amenity, budget band, party type, geography, and booking stage.',decision:'Map AF-044 across inspiration, comparison, and booking-readiness signals.',why:'A traveler exploring a neighborhood needs different evidence from one comparing two hotels tonight.',narration:'Embedding similarity groups the language, then deterministic labels add occasion and booking stage. The result is an audience-intent map, not a set of invented personas.'},
    {id:'freeze',stage:2,lane:0,kind:'data',label:'Versioned intent set v8',summary:'The normalized questions, behavioral labels, synthetic flags, source metadata, and hash are frozen for valid comparisons.',decision:'Freeze 56 questions as version eight.',why:'Movement is only credible when the research instrument does not quietly change.',narration:'The audience-intent set is versioned and frozen. New questions can enter version nine, but they cannot rewrite the history of this study.'},
    {id:'router',stage:2,lane:-1.3,kind:'code',label:'OpenRouter task selector',summary:'High-volume extraction, contested framing, diagnosis, and narrative writing each receive different model routes.',decision:'Use a small extractor, two independent reasoning families, and batch frontier writing.',why:'The observatory spends quality where judgment is contested and keeps high-volume reading economical.',narration:'OpenRouter assigns models by task: cheap structured extraction at volume, independent reasoning families for framing, and frontier batch work only for the weekly narrative.'},
    {id:'schedule',stage:3,lane:0,kind:'code',label:'Repeated probe scheduler',summary:'Each question runs across engines, origin markets, devices, and repeated samples with timestamped execution logs.',decision:'Schedule five samples across three engines and three origin markets.',why:'Answer-engine outputs are stochastic and location-sensitive; one probe cannot support a stable audience claim.',narration:'The scheduler fans the frozen set across engines, origin markets, and repeated samples. Repetition turns one travel answer into a measurement.'},
    {id:'engines',stage:3,lane:1.2,kind:'external',label:'Answer engines',summary:'Complete answers, cited URLs, order, timestamps, engine, and geography are captured as raw observations.',decision:'Store the full response before reducing it to metrics.',why:'Raw observations allow later questions without rerunning the historical instrument.',narration:'The engines are instruments, not judges. Their complete answers and citations are stored so the raw evidence remains available.'},
    {id:'extract',stage:4,lane:0,kind:'model',tier:'OPENROUTER · SMALL',label:'Recommendation + citation extraction',summary:'A schema records hotel presence, position, cited sources, audience language, answer spans, and extraction confidence per sample.',decision:'The hotel appears in 11 of 45 answers and is recommended in 4.',why:'High-volume structured reading does not require a frontier model.',narration:'A small routed model extracts every hotel mention, its position, the audience language around it, and every citation. The independent hotel appears eleven times but earns only four recommendations.'},
    {id:'judges',stage:5,lane:-.75,kind:'model',tier:'OPENROUTER · 2 FAMILIES',label:'Independent framing judges',summary:'Two blind judges classify each mention as recommended, listed, mismatched, neutral, or disputed and quote the answer evidence.',decision:'Agree the hotel owns music-history language but rarely enters design-weekend answers.',why:'Visibility without audience framing can turn an irrelevant mention into a misleading success metric.',narration:'Two model families judge framing independently. They agree that music history is strong, but the hotel rarely enters answers about a design-led weekend.'},
    {id:'variance',stage:5,lane:.55,kind:'code',label:'Variance + confidence bands',summary:'Sample spread becomes an interval by intent and origin market; judge disagreement stays visible.',decision:'Report a 24% recommendation share with a 16–32% interval and high neighborhood-query volatility.',why:'A single percentage conceals the instability decision-makers most need to see.',narration:'Code turns repeated samples into confidence bands by audience intent. Neighborhood questions are volatile, so the study reports a range rather than a false-precision score.'},
    {id:'canonical',stage:6,lane:-1.15,kind:'code',label:'Citation canonicalization',summary:'Redirects, parameters, mirrored domains, and duplicate URLs collapse into stable publisher identities.',decision:'Reduce 74 URLs to 29 canonical publishers.',why:'A source graph should count trusted publishers, not tracking variations.',narration:'Citation URLs are normalized into publisher identities. Seventy-four raw links become twenty-nine canonical sources.'},
    {id:'graph',stage:6,lane:0,kind:'data',label:'Citation influence graph',summary:'Audience intents, answer engines, hotel attributes, publishers, neighborhoods, and recommendations form a traversable evidence graph.',decision:'Identify three travel publishers and two local guides that dominate creative-weekend answers.',why:'The actionable question is where engines already obtain trusted destination evidence.',narration:'The citation graph reveals the travel publishers and local guides that repeatedly shape creative-weekend recommendations. That influence matters more than blindly adding another hotel blog post.'},
    {id:'diagnose',stage:6,lane:1.2,kind:'model',tier:'OPENROUTER · REASONING',label:'Audience opportunity diagnosis',summary:'A reasoning model uses the citation graph, site RAG, structured-data inventory, and observed intent map to draft specific audience opportunities.',decision:'Diagnose a missing neighborhood-and-occasion evidence page plus weak local-guide corroboration.',why:'“Write more travel content” is not an executable audience strategy.',narration:'A reasoning model compares answer evidence with retrieved site content. It finds a missing neighborhood-and-occasion asset and a corroboration gap with trusted local guides.'},
    {id:'score',stage:7,lane:-1.15,kind:'code',label:'Opportunity scoring',summary:'Observed demand, booking proximity, absence, volatility, evidence quality, effort, and expected reach determine priority.',decision:'Rank the creative-weekend destination evidence ticket first.',why:'Deterministic priority survives preference-driven stakeholder debate.',narration:'Opportunities are scored with a visible formula. The creative-weekend evidence gap ranks first because demand is observed, booking intent is near, and the source path is clear.'},
    {id:'readonly',stage:7,lane:0,kind:'gate',label:'GATE · Read-only observatory',summary:'The measurement system holds no website write credentials and can only emit an evidence-linked handoff.',decision:'PASS the backlog to the implementation system.',why:'Measurement should not silently become autonomous optimization.',narration:'The read-only gate prevents this observatory from changing a website. It can measure, diagnose, and hand off—nothing more.'},
    {id:'handoff',stage:7,lane:1.15,kind:'output',label:'Audience growth handoff',summary:'The audience opportunity, citations, confidence bands, intent-set version, partnership targets, and rollback requirements move to an approval-controlled system.',decision:'Queue one evidence-backed content and partnership brief for human approval.',why:'Execution belongs in a separate workflow with approval and rollback controls.',narration:'The final packet carries the audience opportunity, uncertainty, content evidence, and publisher relationships into an approval-controlled growth workflow.'},
    {id:'narrative',stage:7,lane:2.25,kind:'model',tier:'OPENROUTER · FRONTIER BATCH',label:'Audience intelligence brief',summary:'An overnight model writes the research brief in house voice and leads with what changed, for whom, and why it matters.',decision:'Explain the design-weekend gap and the publisher evidence behind it.',why:'The system should turn measurement into a readable audience decision without hiding uncertainty.',narration:'A batch model prepares the audience intelligence brief, leading with the opportunity and linking every claim back to the frozen dataset.'}
  ],
  edges:[['queries','privacy'],['privacy','cluster'],['cluster','freeze'],['freeze','router'],['router','schedule'],['schedule','engines'],['engines','extract'],['extract','judges'],['extract','variance'],['judges','variance'],['variance','canonical'],['canonical','graph'],['graph','diagnose'],['diagnose','score'],['score','readonly'],['readonly','handoff'],['handoff','narrative'],['variance','narrative'],['graph','narrative'],['score','narrative']],
  route:['queries','privacy','cluster','freeze','router','schedule','engines','extract','judges','variance','canonical','graph','diagnose','score','readonly','handoff','narrative'],
  completion:{title:'Audience intent becomes an evidence-backed growth brief.',copy:'Answer Field measures how travelers ask, preserves uncertainty, identifies the publishers shaping recommendations, retrieves the site evidence behind the gaps, and hands one prioritized opportunity to an approval-controlled execution system.',proof:'Intent map + confidence bands',human:'Approves downstream work',write:'Zero observatory writes'}
};
