window.WORKFLOW_CONFIG={
  title:'Proving Ground',kicker:'Evaluation and model-behavior lab',
  headline:'Prove the change before it ships.',
  intro:'Follow one difficult evaluation item through calibrated scoring, independent model families, human adjudication, and a regression gate that can stop a release.',
  stages:['Test item','Calibration','Task routing','System run','Independent judges','Agreement','Adjudication','Regression gate'],
  case:{id:'EV-042',type:'ONE GUIDED EVALUATION',title:'Unsupported consolidation recommendation',summary:'A proposed prompt revision starts making confident merge recommendations when the evidence only supports similarity.',route:'Regression candidate · human adjudication',cardLabel:'Evaluation item',cardSub:'Golden set',cta:'Run the evaluation'},
  nodes:[
    {id:'item',stage:0,lane:0,kind:'data',label:'Golden-set item EV-042',summary:'A frozen input, expected behavior, evidence IDs, and SHA-256 hash make this run exactly reproducible.',decision:'Use the versioned item without modification.',why:'A moving test set can hide regressions by changing the exam.',narration:'We begin with EV-042, a frozen golden-set case. Its input, expected behavior, and evidence are versioned, so this prompt revision faces the same test as the last one.'},
    {id:'mutate',stage:0,lane:-1.4,kind:'model',tier:'OPENROUTER · SMALL',label:'Adversarial mutation',summary:'A low-cost model creates negation, truncation, and injection variants for later human review.',decision:'Generate candidates, but do not admit them automatically.',why:'Model-generated tests need human labels before they become truth.',narration:'A small routed model can expand the bench cheaply, but generated cases never promote themselves into the golden set.'},
    {id:'rubric',stage:0,lane:1.4,kind:'data',label:'Rubric v7',summary:'Anchored 0–3 dimensions define groundedness, authority, completeness, and abstention.',decision:'Pin rubric version seven to this run.',why:'A score is meaningless without stable criteria and anchor examples.',narration:'Every judge receives the same pinned rubric, including examples of what each score actually means.'},
    {id:'labels',stage:0,lane:2.6,kind:'human',label:'Human label pair',summary:'Two independent reviewers establish the practical agreement ceiling for this task.',decision:'Use the reconciled human label as the reference.',why:'The judge cannot claim more certainty than qualified humans can establish.',narration:'Two humans label the held-out slice. Their agreement sets the ceiling the automated judges must clear.'},
    {id:'calibrate',stage:1,lane:0,kind:'gate',label:'GATE · Judge calibration',summary:'Judge-to-human Cohen’s kappa must be at least 0.60 on the held-out slice.',decision:'PASS at κ = 0.71.',why:'The rubric and judges clear the published calibration threshold.',narration:'The judge pair reaches point seven one kappa against the human slice. Below point six, the evaluation would stop here and the rubric would go back for repair.'},
    {id:'router',stage:2,lane:0,kind:'code',label:'OpenRouter task selector',summary:'The registry chooses models by evaluation role, quality floor, independence, latency, and price.',decision:'Route the system run normally; assign judges from two different provider families.',why:'Model choice is a policy decision attached to the task, not a scattered product constant.',narration:'OpenRouter now selects by task. The system under test uses the candidate configuration, while the two judges must come from independent provider families.'},
    {id:'redteam',stage:2,lane:-1.5,kind:'model',tier:'OPENROUTER · ALT',label:'Red-team attacker',summary:'A third family creates prompt-injection and refusal probes at high temperature.',decision:'Keep adversarial results separate but visible.',why:'A model asked to attack its own family tends to share its blind spots.',narration:'A third family supplies adversarial probes, giving the bench pressure the authoring family would not reliably apply to itself.'},
    {id:'system',stage:3,lane:0,kind:'model',tier:'SYSTEM UNDER TEST',label:'Candidate prompt + model',summary:'The proposed production configuration generates a recommendation for the frozen item.',decision:'Recommend merging the two records.',why:'The candidate overweights semantic similarity and underweights authority evidence.',narration:'The candidate system makes the mistake this item was built to expose. It recommends a merge even though the evidence proves only that the pages are similar.'},
    {id:'judges',stage:4,lane:0,kind:'model',tier:'OPENROUTER · 2 FAMILIES',label:'Independent judge pair',summary:'Two blind, temperature-zero judges score the same output and cite the spans behind each score.',decision:'Judge A scores groundedness two; Judge B scores zero.',why:'The two-point split is larger than the allowed per-dimension difference.',narration:'Two independent judges disagree sharply on groundedness. The disagreement is preserved instead of averaged into a reassuring number.'},
    {id:'agreement',stage:5,lane:0,kind:'code',label:'Agreement check',summary:'Deterministic arithmetic compares scores dimension by dimension and tracks disagreement drift.',decision:'ESCALATE because |A − B| = 2.',why:'The published rule permits a maximum one-point difference.',narration:'Code measures the split. Two points exceeds the threshold, so this item cannot enter the aggregate yet.'},
    {id:'tiebreak',stage:6,lane:-.65,kind:'model',tier:'OPENROUTER · FRONTIER',label:'Bounded tie-break',summary:'Only split items reach a higher-cost reasoning model with extended thinking.',decision:'The merge claim is unsupported.',why:'The cited evidence establishes similarity but not duplicate authority.',narration:'A frontier model is affordable here because it sees only the small fraction of disputed items. It agrees that similarity was mistaken for permission to merge.'},
    {id:'human',stage:6,lane:.8,kind:'human',label:'Human adjudication',summary:'A qualified reviewer resolves the remaining ambiguity and can revise the rubric.',decision:'Label the output as a groundedness failure.',why:'Authority interpretation remains accountable to a human reviewer.',narration:'A human makes the final call, records the rationale, and checks whether the rubric needs a clearer anchor for authority claims.'},
    {id:'aggregate',stage:7,lane:-1.4,kind:'code',label:'Score aggregation',summary:'Resolved scores roll up by dimension and compare against the last approved release.',decision:'Groundedness falls below its release floor.',why:'EV-042 changes class under the candidate prompt.',narration:'With the item resolved, deterministic aggregation shows the candidate prompt has pushed groundedness below its floor.'},
    {id:'regression',stage:7,lane:0,kind:'gate',label:'GATE · Regression',summary:'Any dimension below its floor blocks the candidate configuration by default.',decision:'BLOCK the prompt revision.',why:'The system fails closed and attaches the changed-class examples.',narration:'The regression gate blocks the release. There is no override hidden in a prompt and no automatic downgrade to a weaker standard.'},
    {id:'scorecard',stage:7,lane:1.35,kind:'output',label:'Evaluation scorecard',summary:'The artifact shows calibration, disagreement, changed items, red-team results, and the blocked decision.',decision:'Publish the failed evaluation result internally.',why:'A visible failure is evidence that the control system works.',narration:'The final scorecard preserves the failed candidate, the disputed item, and the human rationale. The output is a decision record, not a flattering benchmark.'}
  ],
  edges:[['mutate','item','feedback'],['rubric','calibrate'],['labels','calibrate'],['item','calibrate'],['calibrate','router'],['router','system'],['redteam','system','risk'],['system','judges'],['judges','agreement'],['agreement','tiebreak','risk'],['tiebreak','human','risk'],['human','aggregate'],['aggregate','regression'],['regression','scorecard']],
  route:['item','calibrate','router','system','judges','agreement','tiebreak','human','aggregate','regression','scorecard'],
  completion:{title:'The release is blocked.',copy:'The system catches a confident but unsupported merge recommendation, routes only the disputed item to expensive adjudication, and prevents the candidate prompt from shipping.',proof:'Calibrated regression',human:'Final adjudication',write:'Zero production changes'}
};
